from .parser import Parser, GeneratorLiteral, FilterBlock
from .evaluate_generator import (
  evaluate_generator,
  sampleable_generator,
  total_queues,
  random_evaluate_generator,
)
from .evaluate_filter import evaluate_filter
from collections.abc import Iterator
from itertools import product, chain
from typing import cast
import random


parser = Parser()


def clean_product(*args: Iterator[str]) -> Iterator[str]:
  return ("".join(part) for part in product(*args))


def evaluate_blocks(blocks: list[GeneratorLiteral | FilterBlock]) -> Iterator[str]:
  running_iterators: list[Iterator[str]] = []
  for block in blocks:
    match block:
      case GeneratorLiteral():
        running_iterators.append(iter(evaluate_generator(block)))
      case FilterBlock(expr=expr):

        def filter_func(queue):
          return evaluate_filter(expr, queue)

        running_iterators = [filter(filter_func, clean_product(*running_iterators))]

  # cannot end with GeneratorLiteral so running iterators should only contain one element
  return running_iterators[0]


def parse_pattern(pattern: str) -> list[list[list[GeneratorLiteral | FilterBlock]]]:
  """Parses a given pattern into layered list for patterns to be appended together, patterns to be product together, individual blocks in AST"""
  # can list separate patterns together using semicolons to just append on
  patterns = pattern.split(";")
  parsed = []
  for pattern in patterns:
    # separate into parts where filter will apply
    parts = pattern.split(",")

    # parse everything and put in parsed
    all_blocks = []
    for part in parts:
      blocks = parser.parse(part)

      # starting with filter will just be removed as not filtering anything
      while isinstance(blocks[0], FilterBlock):
        blocks = blocks[1:]

      # GeneratorLiterals at the end can be own separate 'blocks'
      all_blocks_initial_end = len(all_blocks)
      while len(blocks) > 0 and isinstance(blocks[-1], GeneratorLiteral):
        all_blocks.insert(all_blocks_initial_end, [blocks.pop()])

      if len(blocks) > 0:
        all_blocks.insert(all_blocks_initial_end, blocks)

    parsed.append(all_blocks)

  return parsed


def sfinder_pieces(pattern: str) -> Iterator[str]:
  """Get all queues following sfinder pieces notation"""
  running_parts: list[Iterator[str]] = []
  parsed_pattern = parse_pattern(pattern)

  for appending_parts in parsed_pattern:
    running_iterators: list[Iterator[str]] = []
    for blocks in appending_parts:
      running_iterators.append(evaluate_blocks(blocks))

    running_parts.append(clean_product(*running_iterators))

  return chain(*running_parts)


def random_sfinder_pieces(pattern: str) -> str | None:
  """Get a random queue from set generated by sfinder pieces notation"""
  # gets one of the possible queues with uniform randomness
  parsed_pattern = parse_pattern(pattern)

  weights: list[int] = []
  choices: list[str] = []  # choice for each part
  for appending_parts in parsed_pattern:
    weight = 1
    queue_choice = ""
    for blocks in appending_parts:
      if len(blocks) == 1:
        # must be only a GeneratorLiteral and might be able to use faster function
        block = cast(GeneratorLiteral, blocks[0])
        if sampleable_generator(block):
          queue_choice += random_evaluate_generator(block)
          weight *= total_queues(block)
          continue

      evaluated_blocks = tuple(evaluate_blocks(blocks))
      weight *= len(evaluated_blocks)

      # no queues to choose from
      if len(evaluated_blocks) == 0:
        return None

      queue_choice += random.choice(evaluated_blocks)

    weights.append(weight)
    choices.append(queue_choice)

  return random.choices(choices, weights=weights)[0]
